name: My First GitHub Actions
on: [push]
jobs:
    manual-approval:
      name: Manual Approval
      runs-on: ubuntu-latest      
      permissions:
        issues: write  
      steps:
        - name: Await Manual Approval
          uses: trstringer/manual-approval@v1
          with:
            secret: ${{ github.TOKEN }}
            approvers: singhrajgithub # Replace with GitHub usernames, with the free version you can only have an issue assigned to one username
            minimum-approvals: 1
            issue-title: "Manual Approval Required for deployment"
            issue-body: "Please approve or deny the deployment."  
